use cars;

-- ---- READ DATA-------------------
SELECT * FROM CAR_DEKHO;

-- ----TOTAL CARS - TO GET THE COUNT OF TOTAL RECORDS-----------------
SELECT COUNT(*) FROM CAR_DEKHO;

-- ------ HOW MANY CARS WIL BE AVAILABLE IN 2023..?

SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR=2023;

-- ------HOW MANY CARS ARE AVAILABLE IN 2020,2021,2022..?

SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR IN(2020,2021,2022) GROUP BY YEAR;

-- -------TOTAL OF ALL CARS BY YEAR.......

SELECT YEAR,COUNT(*) FROM CAR_DEKHO GROUP BY YEAR;

-- ------- HOW MANY DESIEL CARS WERE THERE IN 2020-----

SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR ="2020" AND FUEL = "DIESEL";

-- ----- HOW MANY PETROL CARS WERE THERE IN 2020..?

SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2020 AND FUEL="PETROL";

-- ---- PRINT ALL THE FUEL(PETROL,DIESEL,CNG) CARS BY YEAR------

SELECT YEAR, COUNT(*) FROM CAR_DEKHO WHERE FUEL = "PETROL" GROUP BY YEAR;
 SELECT YEAR, COUNT(*) FROM CAR_DEKHO WHERE FUEL = "DIESEL"GROUP BY YEAR;
 SELECT YEAR, COUNT(*) FROM CAR_DEKHO WHERE FUEL = "CNG" GROUP BY YEAR;
 
 -- ----- WHICH YEAR HAD MORE THAN 100 CARS..?
 
 SELECT YEAR, COUNT(*) FROM CAR_DEKHO GROUP BY YEAR HAVING COUNT(*)>100;
 
 -- ------- ALL CAR COUNT DETAILS BETWEEN 2015 TO 2023----
 
 SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR BETWEEN 2015 AND 2023;
 
 -- ----- NEED COMPLETE DETAILS OF CARS BETWEEN 2015 AND 2023----
 
 SELECT * FROM CAR_DEKHO WHERE YEAR BETWEEN 2015 AND 2023;
 
 ---------END-----------------------------------------------------------------------------